### ISSUE TITLE
"php.path.reply" doesn't happen on boot

### ISSUE THREAD

**Issue by eznix86** [tweakphp/tweakphp#16]
The code at line https://github.com/tweakphp/tweakphp/blob/c85460a34a3efe9005538adeecfec9078dda85be/src/App.vue#L55
is triggered at boot time of electron, the issue is that `php.path.reply` event listener is not triggered in response of the event.

Possible cause:
- When `php.path` event is sent, the application the IPC is not ready yet.

**Comment by saeedvaziry** [comment]
Closing this as no plan to fix. Now the app opens and asks for entering the PHP path
