### ISSUE TITLE
Using deprecated and buggy modules / npm install warnings

### ISSUE THREAD

**Issue by jpmorby** [tweakphp/tweakphp#21]
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @types/vue-router@2.0.0: This is a stub types definition for vue-router (https://github.com/vuejs/vue-router). ecmarkup provides its own type definitions, so you don\'t need @types/ecmarkup installed!

**Comment by saeedvaziry** [comment]
I checked them, many of them are not direct dependency and can't do anything about them.

vue-router and vue types are deleted now
