### ISSUE TITLE
Invalid Path

### ISSUE THREAD

**Issue by xcrap** [tweakphp/tweakphp#33]
I'm a bit confused, running something on a Laravel project works perfectly, working on a custom php project I get invalid path, what am I missing here ? 

<img width="1132" alt="Screenshot 2024-12-26 at 15 17 55" src="https://github.com/user-attachments/assets/07966c08-5b22-41ce-a702-7e0d332ec982" />
<img width="1132" alt="Screenshot 2024-12-26 at 15 17 50" src="https://github.com/user-attachments/assets/e6cd1b02-eabe-47cb-8d12-873337e1d129" />

**Comment by saeedvaziry** [comment]
So currently TweakPHP supports the following projects:
- Laravel
- Symfony
- Wordpress
- Any composer projects

If your app is a PHP project but doesn't have composer, you might get invalid path because TweakPHP doesn't know what to load and where is your app's starting point

**Comment by xcrap** [comment]
I do have composer but it does not mention any php version it's just for phpmailer, maybe that's the reason ?

**Comment by saeedvaziry** [comment]
it doesn't check for php version inside the composer. it just checks if the autoload.php exists

https://github.com/tweakphp/client/blob/main/src/Loader.php#L31

**Comment by xcrap** [comment]
Oh I see now, he checks for vendor/autoload I have a specific path.

    "config": {
        "vendor-dir": "inc"
    },

Thanks for the info will see what i'll do.

**Comment by xcrap** [comment]
Hi.

Even when i set to defaults vendor folders, php it self works but can't i use require or include ?

```PHP
require __DIR__ . '/inc_config.php';
```

If I do I get.

FATAL ERROR  Failed opening required 'inc_config.php' in phar:/Applications/TweakPHP.app/Contents/Resources/public/client-8.2.phar/vendor/psy/psysh/src/CodeCleaner/RequirePass.php on line 3.
