### ISSUE TITLE
Horizontal scroll does not work.

### ISSUE THREAD

**Issue by luanfreitasdev** [tweakphp/tweakphp#46]
**Describe the bug**
Horizontal scroll does not work.

**To Reproduce**
Make tinker generate a large output capable of scrolling horizontally. Note that the status bar does not allow scrolling.

**Expected behavior**
Being able to scroll vertically by clicking on the scrollbar

**Screenshots**
...

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 10.2]
 - App Version [e.g. 0.2.0]

**Additional context**

**Comment by saeedvaziry** [comment]
I think my last pr broke it. Will fix it

**Comment by saeedvaziry** [comment]
Just checked. nothing to do with my PR. looks like the scrollbar is under the bottom status bar
