### ISSUE TITLE
Linux PopOs issues

### ISSUE THREAD

**Issue by luanfreitasdev** [tweakphp/tweakphp#49]
**Describe the bug**
* Icon
* Title

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/8d88269c-cb63-45d3-a3cb-db703681cd6a)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 10.2]
 - App Version [e.g. 0.2.0]

**Additional context**

**Comment by luanfreitasdev** [comment]
Updates: Icon works in dev mode only

**Comment by saeedvaziry** [comment]
It doesn't work at all on ubuntu

**Comment by saeedvaziry** [comment]
I am giving up on the icon. couldn't make it work on an arm based ubuntu

**Comment by uitlaber** [comment]
how you set php path?
