### ISSUE TITLE
Docker code execution

### ISSUE THREAD

**Issue by saeedvaziry** [tweakphp/tweakphp#9]
TweakPHP should be able to tweak code that is on a docker container

**Comment by luanfreitasdev** [comment]
👀
![image](https://github.com/user-attachments/assets/a99d4585-9ad6-417c-8561-f5e32da1eff7)

**Comment by saeedvaziry** [comment]
Getting exciting 🤩

**Comment by luanfreitasdev** [comment]
@saeedvaziry . It doesn't seem difficult, but it might take a few days. Would you happen to have a flow for me to base it on?

**Comment by luanfreitasdev** [comment]
WIP

**Comment by luanfreitasdev** [comment]
### Updates

* A button with a Docker icon has been created on the right.
* When clicking on the icon, a settings window will appear, and the connection can be applied to the current tab.
* You can refresh the list of containers by clicking the icon next to the title
* The PHP version inside the container is checked when selecting the container.
* It is possible to disable the use of the container.
* The working directory can be customized at any time.
* Information about the container name will appear in the status bar.

![image](https://github.com/user-attachments/assets/19696ef9-b74a-4ca3-8d1d-3ab02b485ef2)

![image](https://github.com/user-attachments/assets/5dffb9dd-142d-4704-a95b-4769ee26efeb)

**Comment by saeedvaziry** [comment]
Looking amazing 🤩

**Comment by corazzi** [comment]
Exciting progress @luanfreitasdev 😍
